

- *Attributes of arrays*: Determining the size, shape, memory consumption, and data types of arrays
- *Indexing of arrays*: Getting and setting the value of individual array elements
- *Slicing of arrays*: Getting and setting smaller subarrays within a larger array
- *Reshaping of arrays*: Changing the shape of a given array
- *Joining and splitting of arrays*: Combining multiple arrays into one, and splitting one array into many

# The Basics of NumPy Arrays

## NumPy Array Attributes

First let's discuss some useful array attributes.
We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array.
We'll use NumPy's random number generator, which we will *seed* with a set value in order to ensure that the same random arrays are generated each time this code is run:

In [ ]:
import numpy as np
 #Array declaration

x1 = np.array([45,89,64,33])  # One-dimensional array
x2 = np.array([[1,2,3],[4,5,6],[7,8,9]])  # Two-dimensional array


In [ ]:
print(x1)

[45 89 64 33]


Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

In [ ]:
print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)

x2 ndim:  2
x2 shape: (3, 3)
x2 size:  9


Another useful attribute is the ``dtype``, the data type of the array (which we discussed previously in [Understanding Data Types in Python](02.01-Understanding-Data-Types.ipynb)):

In [ ]:
x3=np.array([5.5,6.9])
print(x3.dtype)

float64


Other attributes include ``itemsize``, which lists the size (in bytes) of each array element, and ``nbytes``, which lists the total size (in bytes) of the array:

In [ ]:
print( x2.itemsize)
print( x2.nbytes)

8
72


In general, we expect that ``nbytes`` is equal to ``itemsize`` times ``size``.

## Array Indexing: Accessing Single Elements

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar.
In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [ ]:
x1

array([45, 89, 64, 33])

In [ ]:
x1[-2]

64

To index from the end of the array, you can use negative indices:

In [ ]:
x1[-2]

7

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [ ]:
x2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#array(row,column)
x2[1, 2] = 60

In [ ]:
x2

array([[ 1,  2,  3],
       [ 4,  5, 60],
       [ 7,  8,  9]])

Values can also be modified using any of the above index notation:

In [ ]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

## Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### One-dimensional subarrays

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[5:9]

array([5, 6, 7, 8])

In [ ]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [ ]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [ ]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[1::3]  # every other element, starting at index 1

array([1, 4, 7])

### Multi-dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas.
For example:

In [ ]:
x2

array([[ 1,  2,  3],
       [ 4,  5, 60],
       [ 7,  8,  9]])

In [ ]:
x2[0:2, 0:2]  # two rows, three columns

array([[1, 2],
       [4, 5]])

Finally, subarray dimensions can even be reversed together:

#### Accessing array rows and columns

One commonly needed routine is accessing of single rows or columns of an array.
This can be done by combining indexing and slicing, using an empty slice marked by a single colon (``:``):

In [ ]:
x2

array([[ 1,  2,  3],
       [ 4,  5, 60],
       [ 7,  8,  9]])

In [ ]:
print(x2[:, 1])  # first column of x2

[2 5 8]


In [ ]:
print(x2[2, :])  # first row of x2

[7 8 9]


### Creating copies of arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the ``copy()`` method:

In [ ]:
x2_sub_copy =x2.copy()
print(x2_sub_copy)#PURE COPY

[[ 1  2  3]
 [ 4  5 60]
 [ 7  8  9]]


If we now modify this subarray, the original array is not touched:

In [ ]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  2  3]
 [ 4  5 60]
 [ 7  8  9]]


In [ ]:
print(x2)

[[ 1  2  3]
 [ 4  5 60]
 [ 7  8  9]]


## Reshaping of Arrays

Another useful type of operation is reshaping of arrays.
The most flexible way of doing this is with the ``reshape`` method.


Note that for this to work, the size of the initial array must match the size of the reshaped array.


In [ ]:
x = np.array([1, 2, 3,4])

# row vector via reshape
x.reshape((2, 2))

array([[1, 2],
       [3, 4]])

## Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

### Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines ``np.concatenate``, ``np.vstack``, and ``np.hstack``.
``np.concatenate`` takes a tuple or list of arrays as its first argument, as we can see here:

In [ ]:
x = np.array([1, 2, 3])
y = np.array([8, 12, 14])
np.concatenate([x, y])

array([ 1,  2,  3,  8, 12, 14])

You can also concatenate more than two arrays at once:

In [ ]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  8 12 14 99 99 99]


### Splitting of arrays

The opposite of concatenation is splitting, which is implemented by the functions ``np.split``, ``np.hsplit``, and ``np.vsplit``.  For each of these, we can pass a list of indices giving the split points:

In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2 = np.split(x, [2])
print(x1, x2)

[1 2] [ 3 99 99  3  2  1]
